In [45]:
import numpy as np
import pandas as pd

In [46]:
customer_marketing_df = pd.read_csv("C:/Users/Winifred/Ironhack/Part time program/Labs/Python Lab/Lab 9/marketing_customer_analysis.csv")

In [47]:
customer_marketing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Unnamed: 0                     10910 non-null  int64
 1   Customer                       10910 non-null  object
 2   State                          10279 non-null  object
 3   Customer Lifetime Value        10910 non-null  float64
 4   Response                       10279 non-null  object
 5   Coverage                       10910 non-null  object
 6   Education                      10910 non-null  object
 7   Effective To Date              10910 non-null  object
 8   EmploymentStatus               10910 non-null  object
 9   Gender                         10910 non-null  object
 10  Income                         10910 non-null  int64
 11  Location Code                  10910 non-null  object
 12  Marital Status                 10910 non-null  object
 13  Monthly Premium Auto           10910 non-null  int64
 14  Months Since Last Claim        10277 non-null  float64
 15  Months Since Policy Inception  10910 non-null  int64
 16  Number of Open Complaints      10277 non-null  float64
 17  Number of Policies             10910 non-null  int64
 18  Policy Type                    10910 non-null  object
 19  Policy                         10910 non-null  object
 20  Renew Offer Type               10910 non-null  object
 21  Sales Channel                  10910 non-null  object
 22  Total Claim Amount             10910 non-null  float64
 23  Vehicle Class                  10288 non-null  object
 24  Vehicle Size                   10288 non-null  object
 25  Vehicle Type                   5428 non-null   object
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

In [48]:
customer_marketing_df.describe()

,Unnamed: 0,Customer Lifetime Value,Income,Monthly Premium Auto,Months Since Last Claim,Months Since Policy Inception,Number of Open Complaints,Number of Policies,Total Claim Amount
count,10910.000000,10910.000000,10910.000000,10910.000000,10277.000000,10910.000000,10277.000000,10910.000000,10910.000000
mean,5454.500000,8018.241094,37536.284785,93.196059,15.149071,48.091934,0.384256,2.979193,434.888330
std,3149.590053,6885.081434,30359.195670,34.442532,10.080349,27.940675,0.912457,2.399359,292.180556
min,0.000000,1898.007675,0.000000,61.000000,0.000000,0.000000,0.000000,1.000000,0.099007
25%,2727.250000,4014.453113,0.000000,68.000000,6.000000,24.000000,0.000000,1.000000,271.082527
50%,5454.500000,5771.147235,33813.500000,83.000000,14.000000,48.000000,0.000000,2.000000,382.564630
75%,8181.750000,8992.779137,62250.750000,109.000000,23.000000,71.000000,0.000000,4.000000,547.200000
max,10909.000000,83325.381190,99981.000000,298.000000,35.000000,99.000000,5.000000,9.000000,2893.239678

In [49]:
# 1. Make a copy
clean_customer_marketing_df = customer_marketing_df.copy()

In [88]:
clean_customer_marketing_df.duplicated().sum()

np.int64(0)

In [89]:
clean_customer_marketing_df = (
    clean_customer_marketing_df
    .drop_duplicates()
    .reset_index(drop=True)
)

In [90]:
clean_customer_marketing_df.duplicated().sum()

np.int64(0)

In [91]:
clean_customer_marketing_df.columns = (
    clean_customer_marketing_df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_", regex=False)
)

In [56]:
clean_customer_marketing_df.isnull().sum()

unnamed:_0                          0
customer                            0
state                             631
customer_lifetime_value             0
response                          631
coverage                            0
education                           0
effective_to_date                   0
employmentstatus                    0
gender                              0
income                              0
location_code                       0
marital_status                      0
monthly_premium_auto                0
months_since_last_claim           633
months_since_policy_inception       0
number_of_open_complaints         633
number_of_policies                  0
policy_type                         0
policy                              0
renew_offer_type                    0
sales_channel                       0
total_claim_amount                  0
vehicle_class                     622
vehicle_size                      622
vehicle_type                     5482
dtype: int64

In [57]:
clean_customer_marketing_df = clean_customer_marketing_df.drop(
    columns=["vehicle_type"]
)

In [58]:
numeric_columns_with_missing_values = [
    "months_since_last_claim",
    "number_of_open_complaints"
]

for column in numeric_columns_with_missing_values:
    clean_customer_marketing_df[column] = (
        clean_customer_marketing_df[column]
        .fillna(clean_customer_marketing_df[column].median())
    )

In [59]:
categorical_columns_with_missing_values = [
    "state",
    "response"
]

for column in categorical_columns_with_missing_values:
    clean_customer_marketing_df[column] = (
        clean_customer_marketing_df[column]
        .fillna(clean_customer_marketing_df[column].mode()[0])
    )

In [60]:
clean_customer_marketing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10288 non-null  object
 24  vehicle_size                   10288 non-null  object
dtypes: float64(4), int64(5), object(16)
memory usage: 2.1+ MB

In [96]:
clean_customer_marketing_df = clean_customer_marketing_df.drop(
    columns=["unnamed:_0"]
)

In [97]:
clean_customer_marketing_df.isnull().sum()

customer                           0
state                              0
customer_lifetime_value            0
response                           0
coverage                           0
education                          0
effective_to_date                  0
employmentstatus                   0
gender                             0
income                             0
location_code                      0
marital_status                     0
monthly_premium_auto               0
months_since_last_claim            0
months_since_policy_inception      0
number_of_open_complaints          0
number_of_policies                 0
policy_type                        0
policy                             0
renew_offer_type                   0
sales_channel                      0
total_claim_amount                 0
vehicle_class                    622
vehicle_size                     622
month                              0
dtype: int64

In [98]:
low_claim_df = clean_customer_marketing_df[
    (clean_customer_marketing_df["total_claim_amount"] < 1000) &
    (clean_customer_marketing_df["response"] == "Yes")
]

low_claim_df.head()

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,month
3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,49078,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,1
8,FM55990,California,5989.773931,Yes,Premium,College,2011-01-19,Employed,M,66839,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,1
15,CW49887,California,4626.801093,Yes,Basic,Master,2011-01-16,Employed,F,79487,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,1
19,NJ54277,California,3746.751625,Yes,Extended,College,2011-02-26,Employed,F,41479,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,2
27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2011-02-28,Employed,F,63774,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,2

In [99]:
low_claim_df.shape

(1399, 25)

In [100]:
yes_response_df = clean_customer_marketing_df[
    clean_customer_marketing_df["response"] == "Yes"
].copy()

yes_response_df.shape

(1466, 25)

In [101]:
response_analysis_df = (
    yes_response_df
    .groupby(["policy_type", "gender"], as_index=False)
    .agg(
        average_monthly_premium=(
            "monthly_premium_auto", "mean"
        ),
        average_customer_lifetime_value=(
            "customer_lifetime_value", "mean"
        ),
        average_total_claim_amount=(
            "total_claim_amount", "mean"
        ),
        number_of_customers=(
            "customer", "count"
        )
    )
    .round(2)
)

response_analysis_df

,policy_type,gender,average_monthly_premium,average_customer_lifetime_value,average_total_claim_amount,number_of_customers
0,Corporate Auto,F,94.30,7712.63,433.74,169
1,Corporate Auto,M,92.19,7944.47,408.58,154
2,Personal Auto,F,99.00,8339.79,452.97,540
3,Personal Auto,M,91.09,7448.38,457.01,536
4,Special Auto,F,92.31,7691.58,453.28,35
5,Special Auto,M,86.34,8247.09,429.53,32

In [102]:
response_analysis_df.sort_values(
    by="average_customer_lifetime_value",
    ascending=False
)

,policy_type,gender,average_monthly_premium,average_customer_lifetime_value,average_total_claim_amount,number_of_customers
2,Personal Auto,F,99.00,8339.79,452.97,540
5,Special Auto,M,86.34,8247.09,429.53,32
1,Corporate Auto,M,92.19,7944.47,408.58,154
0,Corporate Auto,F,94.30,7712.63,433.74,169
4,Special Auto,F,92.31,7691.58,453.28,35
3,Personal Auto,M,91.09,7448.38,457.01,536

In [103]:
customers_by_state_df = (
    customer_marketing_df
    .dropna(subset=["State"])
    .groupby("State", as_index=False)
    .agg(
        total_customers=("Customer", "nunique")
    )
    .sort_values(
        by="total_customers",
        ascending=False
    )
)

customers_by_state_df

        State  total_customers
1  California             3150
3      Oregon             2601
0     Arizona             1703
2      Nevada              882
4  Washington              798

In [104]:
states_above_500_df = customers_by_state_df[
    customers_by_state_df["total_customers"] > 500
].reset_index(drop=True)

states_above_500_df

        State  total_customers
0  California             3150
1      Oregon             2601
2     Arizona             1703
3      Nevada              882
4  Washington              798

In [105]:
clv_by_education_gender_df = (
    clean_customer_marketing_df
    .groupby(["education", "gender"], as_index=False)
    .agg(
        maximum_customer_lifetime_value=(
            "customer_lifetime_value", "max"
        ),
        minimum_customer_lifetime_value=(
            "customer_lifetime_value", "min"
        ),
        median_customer_lifetime_value=(
            "customer_lifetime_value", "median"
        )
    )
    .round(2)
)

clv_by_education_gender_df

,education,gender,maximum_customer_lifetime_value,minimum_customer_lifetime_value,median_customer_lifetime_value
0,Bachelor,F,73225.96,1904.00,5640.51
1,Bachelor,M,67907.27,1898.01,5548.03
2,College,F,61850.19,1898.68,5623.61
3,College,M,61134.68,1918.12,6005.85
4,Doctor,F,44856.11,2395.57,5332.46
5,Doctor,M,32677.34,2267.60,5577.67
6,High School or Below,F,55277.45,2144.92,6039.55
7,High School or Below,M,83325.38,1940.98,6286.73
8,Master,F,51016.07,2417.78,5729.86
9,Master,M,50568.26,2272.31,5579.10

In [106]:
clv_by_education_gender_df.sort_values(
    by="median_customer_lifetime_value",
    ascending=False
)

,education,gender,maximum_customer_lifetime_value,minimum_customer_lifetime_value,median_customer_lifetime_value
7,High School or Below,M,83325.38,1940.98,6286.73
6,High School or Below,F,55277.45,2144.92,6039.55
3,College,M,61134.68,1918.12,6005.85
8,Master,F,51016.07,2417.78,5729.86
0,Bachelor,F,73225.96,1904.00,5640.51
2,College,F,61850.19,1898.68,5623.61
9,Master,M,50568.26,2272.31,5579.10
5,Doctor,M,32677.34,2267.60,5577.67
1,Bachelor,M,67907.27,1898.01,5548.03
4,Doctor,F,44856.11,2395.57,5332.46

In [107]:
clean_customer_marketing_df["effective_to_date"] = pd.to_datetime(
    clean_customer_marketing_df["effective_to_date"],
    format="%m/%d/%y"
)

clean_customer_marketing_df["month"] = (
    clean_customer_marketing_df["effective_to_date"].dt.month
)

In [108]:
clean_customer_marketing_df[
    ["effective_to_date", "month"]
].head()

  effective_to_date  month
0        2011-02-18      2
1        2011-01-18      1
2        2011-02-10      2
3        2011-01-11      1
4        2011-01-17      1

In [109]:
policies_by_state_month_df = (
    clean_customer_marketing_df
    .groupby(["state", "month"])
    .size()
    .reset_index(name="policies_sold")
)

policies_by_state_month_df.head()

        state  month  policies_sold
0     Arizona      1           1008
1     Arizona      2            929
2  California      1           2231
3  California      2           1952
4      Nevada      1            551

In [110]:
policies_state_month_pivot_df = (
    policies_by_state_month_df
    .pivot(
        index="state",
        columns="month",
        values="policies_sold"
    )
    .fillna(0)
    .astype(int)
)

policies_state_month_pivot_df

month          1     2
state
Arizona     1008   929
California  2231  1952
Nevada       551   442
Oregon      1565  1344
Washington   463   425

In [111]:
total_policies_by_state_df = (
    policies_by_state_month_df
    .groupby("state", as_index=False)["policies_sold"]
    .sum()
    .sort_values(
        by="policies_sold",
        ascending=False
    )
)

total_policies_by_state_df

        state  policies_sold
1  California           4183
3      Oregon           2909
0     Arizona           1937
2      Nevada            993
4  Washington            888

In [112]:
top_3_states = (
    total_policies_by_state_df
    .head(3)["state"]
    .tolist()
)

top_3_states

['California', 'Oregon', 'Arizona']

In [113]:
top_3_states_monthly_df = policies_by_state_month_df[
    policies_by_state_month_df["state"].isin(top_3_states)
]

top_3_states_monthly_df

        state  month  policies_sold
0     Arizona      1           1008
1     Arizona      2            929
2  California      1           2231
3  California      2           1952
6      Oregon      1           1565
7      Oregon      2           1344

In [114]:
top_3_states_pivot_df = (
    top_3_states_monthly_df
    .pivot(
        index="state",
        columns="month",
        values="policies_sold"
    )
    .fillna(0)
    .astype(int)
)

top_3_states_pivot_df

month          1     2
state
Arizona     1008   929
California  2231  1952
Oregon      1565  1344

In [115]:
top_3_states_pivot_df = top_3_states_pivot_df.rename(
    columns={
        1: "January",
        2: "February"
    }
)

top_3_states_pivot_df

month       January  February
state
Arizona        1008       929
California     2231      1952
Oregon         1565      1344

In [116]:
channel_response_wide_df = pd.crosstab(
    clean_customer_marketing_df["response"],
    clean_customer_marketing_df["sales_channel"]
)

channel_response_wide_df

sales_channel  Agent  Branch  Call Center   Web
response
No              3379    2696         1920  1449
Yes              742     326          221   177

In [117]:
channel_response_long_df = (
    channel_response_wide_df
    .reset_index()
    .melt(
        id_vars="response",
        var_name="sales_channel",
        value_name="number_of_customers"
    )
)

channel_response_long_df

  response sales_channel  number_of_customers
0       No         Agent                 3379
1      Yes         Agent                  742
2       No        Branch                 2696
3      Yes        Branch                  326
4       No   Call Center                 1920
5      Yes   Call Center                  221
6       No           Web                 1449
7      Yes           Web                  177

In [118]:
channel_response_long_df["total_customers_in_channel"] = (
    channel_response_long_df
    .groupby("sales_channel")["number_of_customers"]
    .transform("sum")
)

In [119]:
channel_response_long_df["response_rate_percent"] = (
    channel_response_long_df["number_of_customers"]
    / channel_response_long_df["total_customers_in_channel"]
    * 100
).round(2)

In [120]:
yes_response_rate_by_channel_df = (
    channel_response_long_df[
        channel_response_long_df["response"] == "Yes"
    ]
    [
        [
            "sales_channel",
            "number_of_customers",
            "total_customers_in_channel",
            "response_rate_percent"
        ]
    ]
    .sort_values(
        by="response_rate_percent",
        ascending=False
    )
    .reset_index(drop=True)
)

yes_response_rate_by_channel_df

,sales_channel,number_of_customers,total_customers_in_channel,response_rate_percent
0,Agent,742,4121,18.01
1,Web,177,1626,10.89
2,Branch,326,3022,10.79
3,Call Center,221,2141,10.32