In [103]:
import numpy as np
import pandas as pd

In [104]:
customer_insurance_df1 = pd.read_csv("C:/Users/Winifred/Ironhack/Part time program/Week 4/Lab 8 - Data Structuring and Combining/file1.csv")
customer_insurance_df2 = pd.read_csv("C:/Users/Winifred/Ironhack/Part time program/Week 4/Lab 8 - Data Structuring and Combining/file2.csv")
customer_insurance_df3 = pd.read_csv("C:/Users/Winifred/Ironhack/Part time program/Week 4/Lab 8 - Data Structuring and Combining/file3.csv")

In [105]:
combined_df = pd.concat([customer_insurance_df1, customer_insurance_df2,customer_insurance_df3], ignore_index=True)

In [106]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   9137 non-null   object
 1   ST                         2067 non-null   object
 2   GENDER                     1945 non-null   object
 3   Education                  9137 non-null   object
 4   Customer Lifetime Value    9130 non-null   object
 5   Income                     9137 non-null   float64
 6   Monthly Premium Auto       9137 non-null   float64
 7   Number of Open Complaints  9137 non-null   object
 8   Policy Type                9137 non-null   object
 9   Vehicle Class              9137 non-null   object
 10  Total Claim Amount         9137 non-null   float64
 11  State                      7070 non-null   object
 12  Gender                     7070 non-null   object
dtypes: float64(3), object(10)
memory usage: 1.2+ MB

In [107]:
#Replacing the column label for uniformity in the dataset
combined_df = combined_df.rename(columns={"Customer":"customer",
                                                              "ST" : "state", 
                                                              "GENDER" : "gender",
                                                              "Education": "education",
                                                              "Customer Lifetime Value": "customer_lifetime_value",
                                                              "Income" : "income",
                                                              "Monthly Premium Auto" : "monthly_premium_auto",
                                                              "Number of Open Complaints": "number_of_open_complaints",
                                                              "Policy Type" : "policy_type",
                                                              "Vehicle Class": "vehicle_class",
                                                              "Total Claim Amount":" total_claim_amount"                                                        
                                                             })
combined_df.columns

Index(['customer', 'state', 'gender', 'education', 'customer_lifetime_value',
       'income', 'monthly_premium_auto', 'number_of_open_complaints',
       'policy_type', 'vehicle_class', ' total_claim_amount', 'State',
       'Gender'],
      dtype='object')

In [108]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      2067 non-null   object
 2   gender                     1945 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   object
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10   total_claim_amount        9137 non-null   float64
 11  State                      7070 non-null   object
 12  Gender                     7070 non-null   object
dtypes: float64(3), object(10)
memory usage: 1.2+ MB

In [109]:
combined_df[combined_df.duplicated()]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,State,Gender
1072,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4008,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.6,NaN,NaN
4009,CW49887,California,F,Master,462680.11%,79487.0,114.0,1/0/00,Special Auto,SUV,547.2,NaN,NaN
4010,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.6,NaN,NaN

In [110]:
combined_df = combined_df.drop_duplicates()

In [111]:
combined_df[combined_df.duplicated()]

Empty DataFrame
Columns: [customer, state, gender, education, customer_lifetime_value, income, monthly_premium_auto, number_of_open_complaints, policy_type, vehicle_class,  total_claim_amount, State, Gender]
Index: []

In [112]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9135 entries, 0 to 12073
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9134 non-null   object
 1   state                      2064 non-null   object
 2   gender                     1942 non-null   object
 3   education                  9134 non-null   object
 4   customer_lifetime_value    9127 non-null   object
 5   income                     9134 non-null   float64
 6   monthly_premium_auto       9134 non-null   float64
 7   number_of_open_complaints  9134 non-null   object
 8   policy_type                9134 non-null   object
 9   vehicle_class              9134 non-null   object
 10   total_claim_amount        9134 non-null   float64
 11  State                      7070 non-null   object
 12  Gender                     7070 non-null   object
dtypes: float64(3), object(10)
memory usage: 999.1+ KB

In [113]:
combined_df["gender"].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [114]:
combined_df.loc[:, "gender"] = combined_df["gender"].replace({"Femal": "F","Male": "M","female": "F"})

In [115]:
combined_df["gender"].unique()

array([nan, 'F', 'M'], dtype=object)

In [116]:
combined_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA', nan], dtype=object)

In [117]:
combined_df.loc[:,"state"] = combined_df["state"].replace ({'AZ':'Arizona', 'WA':'Washington',  'Cali':'California'})

In [118]:
combined_df["state"].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [119]:
combined_df["education"].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor', nan], dtype=object)

In [120]:
combined_df.loc[:,"education"] = combined_df["education"].replace ({'Bachelors':'Bachelor'})

In [121]:
combined_df["education"].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College', 'Doctor',
       nan], dtype=object)

In [122]:
combined_df["vehicle_class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car', nan], dtype=object)

In [123]:
combined_df.loc[:,"vehicle_class"] = combined_df["vehicle_class"].replace ({'Luxury SUV':"Luxury",
                                                                          'Sports Car':"Luxury",
                                                                          'Luxury Car':"Luxury"})

In [124]:
combined_df["vehicle_class"].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury', nan],
      dtype=object)

In [125]:
clean_customer_insurance_df = combined_df

In [126]:
clean_customer_insurance_df = clean_customer_insurance_df.copy()

In [127]:
clean_customer_insurance_df.dtypes

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value       object
income                       float64
monthly_premium_auto         float64
number_of_open_complaints     object
policy_type                   object
vehicle_class                 object
 total_claim_amount          float64
State                         object
Gender                        object
dtype: object

In [128]:
clean_customer_insurance_df.isnull().sum()

customer                        1
state                        7071
gender                       7193
education                       1
customer_lifetime_value         8
income                          1
monthly_premium_auto            1
number_of_open_complaints       1
policy_type                     1
vehicle_class                   1
 total_claim_amount             1
State                        2065
Gender                       2065
dtype: int64

In [129]:
# Merge the state columns
clean_customer_insurance_df["state"] = (
    clean_customer_insurance_df["state"]
    .fillna(clean_customer_insurance_df["State"])
)

In [130]:
# Merge the gender columns
clean_customer_insurance_df["gender"] = (
    clean_customer_insurance_df["gender"]
    .fillna(clean_customer_insurance_df["Gender"])
)

In [131]:
clean_customer_insurance_df.drop(columns=["State", "Gender"], inplace=True)

In [132]:
clean_customer_insurance_df.isnull().sum()

customer                       1
state                          1
gender                       123
education                      1
customer_lifetime_value        8
income                         1
monthly_premium_auto           1
number_of_open_complaints      1
policy_type                    1
vehicle_class                  1
 total_claim_amount            1
dtype: int64

In [133]:
clean_customer_insurance_df[
    clean_customer_insurance_df["customer_lifetime_value"].isnull()
]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
78,SP81997,Washington,F,Master,NaN,41275.0,96.0,1/0/00,Personal Auto,Four-Door Car,41.122303
988,GT62080,Washington,M,High School or Below,NaN,55561.0,63.0,1/0/00,Personal Auto,Four-Door Car,227.872071
1071,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4333,RI52095,Washington,M,High School or Below,NaN,51878.0,66.0,1/1/00,Personal Auto,Four-Door Car,316.800000
4380,HF88410,Washington,NaN,High School or Below,NaN,36765.0,66.0,1/1/00,Personal Auto,Four-Door Car,320.849072
4588,MW80236,Washington,M,Master,NaN,0.0,70.0,1/0/00,Personal Auto,Four-Door Car,336.000000
4869,TO60700,Washington,F,Bachelor,NaN,25859.0,74.0,1/0/00,Special Auto,Four-Door Car,355.200000

In [134]:
clean_customer_insurance_df["customer_lifetime_value"] = (
    clean_customer_insurance_df["customer_lifetime_value"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

clean_customer_insurance_df["customer_lifetime_value"] = pd.to_numeric(
    clean_customer_insurance_df["customer_lifetime_value"],
    errors="coerce"
)

In [135]:
clean_customer_insurance_df["customer_lifetime_value"] = (
    clean_customer_insurance_df["customer_lifetime_value"]
    .fillna(clean_customer_insurance_df["customer_lifetime_value"].median())
)

In [136]:
clean_customer_insurance_df["customer_lifetime_value"].isnull().sum()

np.int64(0)

In [137]:
numeric_columns = [
    "income",
    "monthly_premium_auto",
    "number_of_open_complaints",
    " total_claim_amount"
]

for col in numeric_columns:
    clean_customer_insurance_df[col] = pd.to_numeric(
        clean_customer_insurance_df[col],
        errors="coerce"
    )

In [138]:
for col in numeric_columns:
    clean_customer_insurance_df[col] = clean_customer_insurance_df[col].fillna(
        clean_customer_insurance_df[col].median()
    )

In [139]:
clean_customer_insurance_df.isnull().sum()

customer                       1
state                          1
gender                       123
education                      1
customer_lifetime_value        0
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    1
vehicle_class                  1
 total_claim_amount            0
dtype: int64

In [140]:
clean_customer_insurance_df["gender"].value_counts(dropna=False)

gender
F      4604
M      4408
NaN     123
Name: count, dtype: int64

In [141]:
clean_customer_insurance_df[
    clean_customer_insurance_df["gender"].isna()
].head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,7714.623619,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
11,VQ65197,California,NaN,College,819719.710000,0.0,110.0,0.0,Personal Auto,SUV,528.000000
12,DP39365,California,NaN,Master,879879.700000,77026.0,110.0,0.0,Corporate Auto,Four-Door Car,472.029737
13,SJ95423,Arizona,NaN,High School or Below,881901.890000,99845.0,110.0,0.0,Corporate Auto,SUV,528.000000
14,IL66569,California,NaN,College,538443.170000,83689.0,70.0,0.0,Corporate Auto,Four-Door Car,307.139132

In [142]:
clean_customer_insurance_df["gender"] = clean_customer_insurance_df["gender"].fillna(
    clean_customer_insurance_df["gender"].mode()[0]
)

In [143]:
clean_customer_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9135 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9134 non-null   object
 1   state                      9134 non-null   object
 2   gender                     9135 non-null   object
 3   education                  9134 non-null   object
 4   customer_lifetime_value    9135 non-null   float64
 5   income                     9135 non-null   float64
 6   monthly_premium_auto       9135 non-null   float64
 7   number_of_open_complaints  9135 non-null   float64
 8   policy_type                9134 non-null   object
 9   vehicle_class              9134 non-null   object
 10   total_claim_amount        9135 non-null   float64
dtypes: float64(5), object(6)
memory usage: 856.4+ KB

In [144]:
clean_customer_insurance_df["number_of_open_complaints"].unique()

array([0., 2., 3., 1., 5., 4.])

In [145]:
clean_customer_insurance_df["number_of_open_complaints"] = (
    clean_customer_insurance_df["number_of_open_complaints"].astype(int)
)

In [146]:
clean_customer_insurance_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9135 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9134 non-null   object
 1   state                      9134 non-null   object
 2   gender                     9135 non-null   object
 3   education                  9134 non-null   object
 4   customer_lifetime_value    9135 non-null   float64
 5   income                     9135 non-null   float64
 6   monthly_premium_auto       9135 non-null   float64
 7   number_of_open_complaints  9135 non-null   int64
 8   policy_type                9134 non-null   object
 9   vehicle_class              9134 non-null   object
 10   total_claim_amount        9135 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 856.4+ KB

In [147]:
clean_customer_insurance_df[
    clean_customer_insurance_df.isnull().any(axis=1)
]

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
1071,NaN,NaN,F,NaN,7714.623619,34240.0,83.0,0,NaN,NaN,377.505619

In [148]:
clean_customer_insurance_df = clean_customer_insurance_df.dropna()

In [149]:
clean_customer_insurance_df[
    clean_customer_insurance_df.isnull().any(axis=1)
]

Empty DataFrame
Columns: [customer, state, gender, education, customer_lifetime_value, income, monthly_premium_auto, number_of_open_complaints, policy_type, vehicle_class,  total_claim_amount]
Index: []

In [150]:
customer_marketing_df = pd.read_csv("C:/Users/Winifred/Ironhack/Part time program/Week 4/Lab 8 - Data Structuring and Combining/marketing_customer_analysis_clean.csv")

In [151]:
customer_marketing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

In [152]:
customer_marketing_df = customer_marketing_df.drop(columns=["unnamed:_0"])

In [153]:
customer_marketing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer                       10910 non-null  object
 1   state                          10910 non-null  object
 2   customer_lifetime_value        10910 non-null  float64
 3   response                       10910 non-null  object
 4   coverage                       10910 non-null  object
 5   education                      10910 non-null  object
 6   effective_to_date              10910 non-null  object
 7   employmentstatus               10910 non-null  object
 8   gender                         10910 non-null  object
 9   income                         10910 non-null  int64
 10  location_code                  10910 non-null  object
 11  marital_status                 10910 non-null  object
 12  monthly_premium_auto           10910 non-null  int64
 13  months_since_last_claim        10910 non-null  float64
 14  months_since_policy_inception  10910 non-null  int64
 15  number_of_open_complaints      10910 non-null  float64
 16  number_of_policies             10910 non-null  int64
 17  policy_type                    10910 non-null  object
 18  policy                         10910 non-null  object
 19  renew_offer_type               10910 non-null  object
 20  sales_channel                  10910 non-null  object
 21  total_claim_amount             10910 non-null  float64
 22  vehicle_class                  10910 non-null  object
 23  vehicle_size                   10910 non-null  object
 24  vehicle_type                   10910 non-null  object
 25  month                          10910 non-null  int64
dtypes: float64(4), int64(5), object(17)
memory usage: 2.2+ MB

In [154]:
customer_marketing_df.describe()

,customer_lifetime_value,income,monthly_premium_auto,months_since_last_claim,months_since_policy_inception,number_of_open_complaints,number_of_policies,total_claim_amount,month
count,10910.000000,10910.000000,10910.000000,10910.000000,10910.000000,10910.000000,10910.000000,10910.000000,10910.000000
mean,8018.241094,37536.284785,93.196059,15.149071,48.091934,0.384256,2.979193,434.888330,1.466728
std,6885.081434,30359.195670,34.442532,9.783520,27.940675,0.885589,2.399359,292.180556,0.498915
min,1898.007675,0.000000,61.000000,0.000000,0.000000,0.000000,1.000000,0.099007,1.000000
25%,4014.453113,0.000000,68.000000,7.000000,24.000000,0.000000,1.000000,271.082527,1.000000
50%,5771.147235,33813.500000,83.000000,15.000000,48.000000,0.000000,2.000000,382.564630,1.000000
75%,8992.779137,62250.750000,109.000000,23.000000,71.000000,0.384256,4.000000,547.200000,2.000000
max,83325.381190,99981.000000,298.000000,35.000000,99.000000,5.000000,9.000000,2893.239678,2.000000

In [155]:
customer_marketing_df.isnull().sum()

customer                         0
state                            0
customer_lifetime_value          0
response                         0
coverage                         0
education                        0
effective_to_date                0
employmentstatus                 0
gender                           0
income                           0
location_code                    0
marital_status                   0
monthly_premium_auto             0
months_since_last_claim          0
months_since_policy_inception    0
number_of_open_complaints        0
number_of_policies               0
policy_type                      0
policy                           0
renew_offer_type                 0
sales_channel                    0
total_claim_amount               0
vehicle_class                    0
vehicle_size                     0
vehicle_type                     0
month                            0
dtype: int64

In [156]:
customer_marketing_df.duplicated().sum()

np.int64(443)

In [157]:
customer_marketing_df[customer_marketing_df.duplicated()].head()

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
644,SK12432,Arizona,2388.353882,No,Basic,Bachelor,2011-02-14,Unemployed,M,0,...,1,Personal Auto,Personal L1,Offer2,Web,677.970934,Four-Door Car,Medsize,A,2
645,BZ85280,Oregon,7284.262288,No,Basic,College,2011-02-23,Medical Leave,M,10334,...,2,Personal Auto,Personal L1,Offer3,Agent,296.962938,Four-Door Car,Medsize,A,2
707,KX23516,California,4455.843406,No,Extended,High School or Below,2011-02-20,Unemployed,F,0,...,1,Personal Auto,Personal L3,Offer4,Agent,699.615192,SUV,Medsize,A,2
895,ON44465,California,5313.294035,No,Extended,High School or Below,2011-01-24,Unemployed,F,0,...,9,Personal Auto,Personal L2,Offer1,Agent,863.394700,Four-Door Car,Medsize,A,1
901,YZ19736,Arizona,2580.849899,Yes,Basic,College,2011-02-09,Employed,M,46900,...,1,Personal Auto,Personal L2,Offer2,Web,316.800000,Four-Door Car,Medsize,A,2

In [158]:
customer_marketing_df = customer_marketing_df.drop_duplicates()

In [159]:
customer_marketing_df.duplicated().sum()

np.int64(0)

In [160]:
sales_channel_revenue = customer_marketing_df.pivot_table(
    index="sales_channel",
    values="customer_lifetime_value",
    aggfunc="sum"
).round(2)

sales_channel_revenue

               customer_lifetime_value
sales_channel
Agent                      31822870.96
Branch                     23545858.75
Call Center                16550431.05
Web                        12118527.39

1.The Agent sales channel generated the highest total customer lifetime value, with 33.06 million, making it the strongest contributor to overall revenue.
2.Branch ranked second, generating 24.36 million in customer lifetime value.
3.The Call Center contributed 17.36 million, indicating a moderate level of revenue generation.
4.The Web channel generated the lowest total customer lifetime value, at 12.70 million, suggesting it contributes less revenue than the other channels.
5.Overall, traditional sales channels (Agents and Branches) appear to generate more valuable customers than digital channels, which may indicate opportunities to strengthen online sales or optimize digital marketing strategies.

In [161]:
clv_gender_education = customer_marketing_df.pivot_table(
    index="education",
    columns="gender",
    values="customer_lifetime_value",
    aggfunc="mean"
).round(2)

clv_gender_education

gender                      F        M
education
Bachelor              7913.45  7713.30
College               7755.03  8086.29
Doctor                7369.59  7414.86
High School or Below  8616.66  8162.36
Master                8226.36  8154.61

1.Customers with High School or Below education have the highest average customer lifetime value for both females (8,616.66) and males (8,162.36).
2.Customers with a Doctor degree have the lowest average customer lifetime value for both genders.
3.For Bachelor, High School or Below, and Master education levels, female customers have a slightly higher average customer lifetime value than male customers.
4.For College and Doctor education levels, male customers have a slightly higher average customer lifetime value.
5.Overall, the differences between male and female customers within each education level are relatively small, suggesting that education level appears to have a stronger relationship with customer lifetime value than gender.

In [162]:
complaints_by_policy_month = (
    customer_marketing_df
    .groupby(["policy_type", "month"], as_index=False)["number_of_open_complaints"]
    .sum()
    .rename(columns={"number_of_open_complaints": "total_complaints"})
)

complaints_by_policy_month

      policy_type  month  total_complaints
0  Corporate Auto      1        419.282184
1  Corporate Auto      2        369.671110
2   Personal Auto      1       1671.378904
3   Personal Auto      2       1398.841880
4    Special Auto      1         83.689793
5    Special Auto      2         85.842561