In [161]:
import numpy as np
import pandas as pd

In [162]:
customer_insurance_df = pd.read_csv("C:/Users/Winifred/Ironhack/Part time program/Week 3/Customer_Insurance_Lab6.csv")

In [163]:
#The no. of rows and columns of the original data set
customer_insurance_df

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [164]:
customer_insurance_df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [165]:
customer_insurance_df.tail()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [166]:
customer_insurance_df.sample()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
475,NS10490,Oregon,F,Bachelor,1415861.36%,83235.0,70.0,1/0/00,Personal Auto,Two-Door Car,336.0

In [167]:
#Dropping rows with null values
print("Before dropna:", customer_insurance_df.shape)

Before dropna: (4008, 11)

In [168]:
clean_customer_insurance_df = customer_insurance_df.dropna(subset=["Customer"])
clean_customer_insurance_df

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955.03%,38644.0,78.0,1/1/00,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76%,63209.0,102.0,1/2/00,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11%,79487.0,114.0,1/0/00,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

In [169]:
clean_customer_insurance_df = clean_customer_insurance_df.copy()

In [170]:
print("After dropna :", clean_customer_insurance_df.shape)

After dropna : (1071, 11)

In [171]:
print(clean_customer_insurance_df.duplicated().sum())

0

In [172]:
clean_customer_insurance_df.isnull().sum()

Customer                       0
ST                             0
GENDER                       117
Education                      0
Customer Lifetime Value        3
Income                         0
Monthly Premium Auto           0
Number of Open Complaints      0
Policy Type                    0
Vehicle Class                  0
Total Claim Amount             0
dtype: int64

In [173]:
clean_customer_insurance_df[clean_customer_insurance_df["Customer Lifetime Value"].isnull()]

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
78,SP81997,Washington,F,Master,NaN,41275.0,96.0,1/0/00,Personal Auto,Four-Door Car,41.122303
988,GT62080,Washington,M,High School or Below,NaN,55561.0,63.0,1/0/00,Personal Auto,Four-Door Car,227.872071

In [174]:
#Identifying the data type of each column
clean_customer_insurance_df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [175]:
clean_customer_insurance_df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [176]:
clean_customer_insurance_df.loc[:,"Customer Lifetime Value"] = (clean_customer_insurance_df["Customer Lifetime Value"].astype(str).str.replace(',', '').str.replace('%', '').astype(float))

clean_customer_insurance_df["Customer Lifetime Value"] = pd.to_numeric(
    clean_customer_insurance_df["Customer Lifetime Value"],
    errors='coerce')

In [177]:
clean_customer_insurance_df.loc[:,'Number of Open Complaints'] = clean_customer_insurance_df['Number of Open Complaints'].str.split('/').str[0].astype(int)

In [178]:
clean_customer_insurance_df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value      float64
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [179]:
clean_customer_insurance_df['Number of Open Complaints'].isnull().sum()

np.int64(0)

In [180]:
clean_customer_insurance_df.loc[:,'Number of Open Complaints'] = (clean_customer_insurance_df['Number of Open Complaints'].astype(str).str.split('/').str[0].str.strip())

In [181]:
clean_customer_insurance_df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value      float64
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [182]:
clean_customer_insurance_df['Number of Open Complaints'].unique()

array(['1'], dtype=object)

In [184]:
clean_customer_insurance_df['Number of Open Complaints'] = (clean_customer_insurance_df['Number of Open Complaints'].astype(str) .str.split('/').str[0].str.strip())

In [185]:
clean_customer_insurance_df['Number of Open Complaints'] = pd.to_numeric(clean_customer_insurance_df['Number of Open Complaints'],errors='coerce')

In [186]:
clean_customer_insurance_df['Number of Open Complaints'] = (clean_customer_insurance_df['Number of Open Complaints'].astype('Int64'))

In [187]:
clean_customer_insurance_df.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value      float64
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints      Int64
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [189]:
clean_customer_insurance_df['Number of Open Complaints'].isnull().sum()

np.int64(0)

In [190]:
# Customer : it is an ID can be combination of numbers and strings
#ST : State has to be an object
#GENDER, Policy Type, Vehicle Class: It is categorial and can be male, female thus object
#Education: Descriptive with names thus object
#Customer Lifetime Value,Income,Monthly Premium Auto,Total Claim Amount    : this is arrived in numbers thus float64
#Number of Open Complaints: these have to be whole numbers thus  Int64

## Identifying Unique values of columns

In [203]:
clean_customer_insurance_df.nunique()

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       1
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [204]:
#Likely categorical columns (based on dtype + meaning): Customer ,ST ,GENDER, Education, Policy Type, Vehicle Class

# These are categorical because they represent labels/groups. We cannot categories customers based on the income or policy value or any column that includes float or integers

#The dataset contains a mix of categorical and numerical variables. Categorical columns such as Gender, Education, Policy Type, and Vehicle Class have a limited number of unique values and are suitable for grouping and segmentation analysis. Numerical variables such as Customer Lifetime Value, Income, and Total Claim Amount show a wide range of values and may contain outliers. The Customer column acts as a unique identifier and is not useful for predictive analysis.

In [205]:
numerical_cols = [
    'Customer Lifetime Value',
    'Income',
    'Monthly Premium Auto',
    'Number of Open Complaints',
    'Total Claim Amount'
]

print("Mean:")
print(clean_customer_insurance_df[numerical_cols].mean())
print("\nMedian:")
print(clean_customer_insurance_df[numerical_cols].median())
print("\nMode:")
print(clean_customer_insurance_df[numerical_cols].mode().iloc[0])
print("\nStandard Deviation:")
print(clean_customer_insurance_df[numerical_cols].std())
print("\nQuartiles:")
print(clean_customer_insurance_df[numerical_cols].quantile([0.25, 0.5, 0.75]))

Mean:
Customer Lifetime Value      793690.259345
Income                        39295.701214
Monthly Premium Auto             193.23436
Number of Open Complaints              1.0
Total Claim Amount              404.986909
dtype: Float64

Median:
Customer Lifetime Value      588174.235
Income                          36234.0
Monthly Premium Auto               83.0
Number of Open Complaints           1.0
Total Claim Amount           354.729129
dtype: Float64

Mode:
Customer Lifetime Value      251459.2
Income                            0.0
Monthly Premium Auto             65.0
Number of Open Complaints         1.0
Total Claim Amount              321.6
Name: 0, dtype: Float64

Standard Deviation:
Customer Lifetime Value      643478.410278
Income                         30469.42706
Monthly Premium Auto           1601.190369
Number of Open Complaints              0.0
Total Claim Amount               293.02726
dtype: Float64

Quartiles:
      Customer Lifetime Value   Income  Monthly Premium Auto  \
0.25              403407.9950  14072.0                  68.0
0.50              588174.2350  36234.0                  83.0
0.75              896287.1975  64631.0                 109.5

      Number of Open Complaints  Total Claim Amount
0.25                        1.0          202.157702
0.50                        1.0          354.729129
0.75                        1.0          532.800000

In [207]:

categorical_cols = ['Customer','ST','GENDER','Education','Policy Type','Vehicle Class']
clean_customer_insurance_df[categorical_cols].describe()

       Customer      ST GENDER Education    Policy Type  Vehicle Class
count      1071    1071    954      1071           1071           1071
unique     1071       8      5         6              3              6
top     RB50392  Oregon      F  Bachelor  Personal Auto  Four-Door Car
freq          1     320    457       324            780            576

In [209]:
location_counts = clean_customer_insurance_df['ST'].value_counts()
print(location_counts)

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

In [211]:
least_common_locations  =location_counts.sort_values(ascending=True).head()
print(least_common_locations)

ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

In [213]:
policy_counts = clean_customer_insurance_df['Policy Type'].value_counts()
print(policy_counts)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [223]:
top_policy = policy_counts.index[0]
print("Policy type with highest number of policies sold :", top_policy)

Policy type with highest number of policies sold : Personal Auto

In [227]:
personal_auto_df = clean_customer_insurance_df.loc[clean_customer_insurance_df['Policy Type'] == 'Personal Auto']

In [228]:
corporate_auto_df = clean_customer_insurance_df.loc[clean_customer_insurance_df['Policy Type'] == 'Corporate Auto']

In [229]:
personal_avg_income = personal_auto_df['Income'].mean()
corporate_avg_income = corporate_auto_df['Income'].mean()

In [232]:
print(f"Average Income for Personal Auto: {personal_avg_income}")
print(f"Average Income for Corporate Auto: {corporate_avg_income}")

Average Income for Personal Auto: 38180.69871794872
Average Income for Corporate Auto: 41390.31196581197

In [233]:
if personal_avg_income < corporate_avg_income:
    print("Personal Auto customers have LOWER income than Corporate Auto customers")
elif personal_avg_income > corporate_avg_income:
    print("Personal Auto customers have HIGHER income than Corporate Auto customers")
else:
    print("Both groups have the SAME average income")

Personal Auto customers have LOWER income than Corporate Auto customers